import { useState, useEffect } from 'react';
import Head from 'next/head'
import Table from '../Components/Table';
import CardsCarousel from '../Components/CardsCarousel ';
import NavBar from '../Components/NavBar';
import HighLightsCards from '../Components/HighLightsCards';
import AntdTable from '../Components/AntdTable';

function Home({ coinsData }) {


  const [state, setstate] = useState(false)

  const stateHandler = (state) => {
    setstate(state)
  }



  return (


    <div >
      <Head>
        <title>Usd Vault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Red Hat Display" />
      </Head>


      {/* <NavBar /> */}
      <CardsCarousel showCard={stateHandler} state={state} />
      <HighLightsCards showState={state} />
      {/* <Table coins={coinsData} /> */}
      <AntdTable datas={coinsData} />
    </div>
  )
}



// export async function getServerSideProps({ query: page = 1 }) {

//   // // Fetch the first page as default
//   const { page = 1, limit = 10 } = query
//   // const page = query.page || 1
//   let coinsData = null
//   // Fetch data from external API
//   try {
//     const res = await fetch(`http://api.usdvault.com/get/table?page=${page}`)
//     if (res.status !== 200) {
//       throw new Error("Failed to fetch")
//     }
//     coinsData = await res.json()
//   } catch (err) {
//     coinsData = { error: { message: err.message } }
//   }
//   // Pass data to the page via props

//   return {
//     props: {
//       coinsData,
//       page: +page
//     }
//   }
// }


export default Home
