import { useState } from 'react';
import Head from 'next/head' 
import Table from '../Components/Table';
import CardsCarousel from '../Components/CardsCarousel ';
import NavBar from '../Components/NavBar';
import HighLightsCards from '../Components/HighLightsCards';
function Home() {




  const [state, setstate] = useState(false)

  const stateHandler = (state) => {
    setstate(state)
  }

  return (


    <div >
      <Head>
        <title>Usd Vault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"></link>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Red Hat Display"></link>
      </Head>

      <NavBar />
      <CardsCarousel showCard={stateHandler} state={state} />
      <HighLightsCards showState={state} />
      <Table />
    </div>
  )
}
export default Home
